# -*- coding: utf-8 -*-
"""Actividad_3_MLPClasificacion_Tensorflow_Pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DyXNvbze_exA6-TcL4Zm8MHXmH3KUfC

<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Actividad 3: Clasificación con una Red Neuronal Profunda con TensorFlow y Pytorch</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> Construir, entrenar y evaluar un MLP profundo en TensorFlow y Pytorch sobre un conjunto de datos real, aplicando las técnicas vistas (regularización, optimizadores, curvas de aprendizaje).
</div>

### Instrucciones

Trabajaremos con el dataset de imágenes **CIFAR-10**: 60 000 imágenes a color de $32\times32$ píxeles (50 000 de entrenamiento y 10 000 de prueba) repartidas en **10 clases** (avión, automóvil, pájaro, gato, ciervo, perro, rana, caballo, barco, camión). Está disponible de forma nativa tanto en TensorFlow (`keras.datasets.cifar10`) como en PyTorch (`torchvision.datasets.CIFAR10`).

1. **Carga y explora** el dataset: normaliza los píxeles a $[0, 1]$, **aplana** cada imagen a un vector de $32\times32\times3 = 3072$ valores (para el MLP) y **visualiza** algunos ejemplos con su clase.
2. Divide en train/validación y usa el conjunto de prueba oficial.
3. Construye un **MLP profundo con Tensorflow** (**Modelo 1**): al menos 3 capas ocultas, con `BatchNormalization`, `Dropout` y optimizador **Adam**. Define la entrada con `keras.Input(shape=(3072,))`. Entrena y reporta la precisión en test.
4. Construye el **mismo MLP con PyTorch** (**Modelo 2**): entrena con **AdamW** y un **scheduler** de tu elección (p. ej. `StepLR` o `CosineAnnealingLR`).
5. Grafica las **curvas de aprendizaje** (pérdida y precisión) de ambos modelos y reporta la **precisión en test**.
6. Muestra la **matriz de confusión** e identifica qué clases se confunden más.
7. **Compara** ambas implementaciones y anota tus conclusiones.

> un MLP sobre imágenes a color suele alcanzar ~45–55 % de precisión en CIFAR-10. Es un buen punto de partida para motivar el uso de **redes convolucionales (CNN)** más adelante.

### 0. Carga y exploración del dataset (CIFAR-10)

Esta parte ya está resuelta: carga el dataset, lo normaliza, lo aplana y muestra algunos ejemplos. Reutilizarás estas variables (`X_train`, `y_train`, `X_test`, `y_test`) en ambos modelos.
"""

import os

# Evita el conflicto de múltiples runtimes OpenMP (MKL + libgomp) en Windows
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import cifar10

# Nombres de las 10 clases de CIFAR-10
class_names = ['avión', 'automóvil', 'pájaro', 'gato', 'ciervo',
               'perro', 'rana', 'caballo', 'barco', 'camión']

# Cargar el dataset (imágenes 32x32x3, etiquetas 0-9)
(X_train_img, y_train), (X_test_img, y_test) = cifar10.load_data()
y_train, y_test = y_train.ravel(), y_test.ravel()   # de (N,1) a (N,)

# Normalizar a [0,1] y aplanar a vectores de 3072 (para el MLP)
X_train = (X_train_img / 255.0).reshape(-1, 32 * 32 * 3).astype('float32')
X_test  = (X_test_img  / 255.0).reshape(-1, 32 * 32 * 3).astype('float32')

print('Entrenamiento:', X_train.shape, '| Prueba:', X_test.shape)
print('Clases:', np.unique(y_train))

# Visualizar 15 imágenes con su clase
plt.figure(figsize=(12, 6))
for i in range(15):
    plt.subplot(3, 5, i + 1)
    plt.imshow(X_train_img[i])          # imagen original a color
    plt.title(class_names[y_train[i]], fontsize=10)
    plt.axis('off')
plt.tight_layout()
plt.show()

"""### 1. Modelo con TensorFlow"""

import tensorflow as tf

# TODO 1: construye un MLP profundo con la API Sequential
#   - keras.Input(shape=(3072,))
#   - >= 3 capas Dense ocultas (p. ej. 512, 256, 128) con activación 'relu'
#   - usa BatchNormalization y Dropout entre capas
#   - capa de salida Dense(10, activation='softmax')

model_tf = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(3072,)),
    tf.keras.layers.Dense(units=512, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(units=256, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(units=128, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(units=10, activation='softmax')

])

model_tf.summary()

# TODO 2: compila con optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']
model_tf.compile(optimizer='adam', loss= 'sparse_categorical_crossentropy', metrics = ['accuracy'])

# TODO 3: entrena guardando el history (usa validation_split=0.1 y varias épocas)
history_tf = model_tf.fit(X_train, y_train, batch_size = 3072, epochs = 10, verbose = 1, validation_split= 0.1)

# TODO 4: evalúa en test e imprime la precisión
test_loss, test_accuracy = model_tf.evaluate(X_test, y_test)

print(f"Accuracy de entrenamiento: {history_tf.history['accuracy'][-1] * 100:.2f}%")
print(f"Accuracy de validación: {history_tf.history['val_accuracy'][-1] * 100:.2f}%")
print(f"Perdida de validación: {history_tf.history['val_loss'][-1]:.2f}")
print(f"Precisión en test: {test_accuracy*100:.2f}")
print(f"Perdida test: {test_loss:.2f}")

"""### 2. Modelo con Pytorch"""

import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

torch.manual_seed(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Reutilizamos los MISMOS datos de CIFAR-10 ya normalizados y aplanados (3072)
X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train, dtype=torch.long)
X_test_t  = torch.tensor(X_test,  dtype=torch.float32)
y_test_t  = torch.tensor(y_test,  dtype=torch.long)

# TODO 1: separa un 10% del entrenamiento para validación
train_size = int(0.9 * len(X_train_t))
val_size = len(X_train_t) - train_size
train_ds = TensorDataset(X_train_t[:-val_size], y_train_t[:-val_size])
val_ds = TensorDataset(X_train_t[-val_size:], y_train_t[-val_size:])
test_ds = TensorDataset(X_test_t, y_test_t)

train_loader = DataLoader(train_ds, batch_size=128, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=128, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=128, shuffle=False)


# TODO 2: crea TensorDataset y DataLoader (train/val/test) con batch_size=128
print('Tensores listos:', X_train_t.shape, X_test_t.shape, '| Dispositivo:', device)

# TODO 3: define tu MLP profundo (>= 3 capas ocultas, BatchNorm, Dropout)
#   Entrada: 3072 features -> salida: 10 clases (logits, sin softmax)
class MiMLP(nn.Module):
    def __init__(self, num_features=3072, num_classes=10):
        super().__init__()
        self.fc1 = nn.Linear(num_features, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, 128)
        self.fc4 = nn.Linear(128, num_classes)
        self.relu = nn.ReLU()
        self.bn1 = nn.BatchNorm1d(512)
        self.bn2 = nn.BatchNorm1d(256)
        self.bn3 = nn.BatchNorm1d(128)
        self.dropout = nn.Dropout(0.3)
        pass

    def forward(self, x):
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.bn2(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc3(x)
        x = self.bn3(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc4(x)
        return x
        # ... completa aquí (nn.Linear, nn.BatchNorm1d, nn.ReLU, nn.Dropout) ...
        pass

net = MiMLP()
print(net)

# TODO 4: bucle de entrenamiento con AdamW + scheduler
model = MiMLP().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)

def run_epoch(loader, entrenar=True):
    model.train() if entrenar else model.eval()
    loss_tot, aciertos, total = 0.0, 0, 0
    contexto = torch.enable_grad() if entrenar else torch.no_grad()
    with contexto:
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            if entrenar:
                optimizer.zero_grad()        # 1. limpiar gradientes
            logits = model(xb)            # 2. forward
            loss = criterion(logits, yb)     # 3. pérdida
            if entrenar:
                loss.backward()              # 4. backward
                optimizer.step()             # 5. actualizar pesos
            loss_tot += loss.item() * xb.size(0)
            aciertos += (logits.argmax(1) == yb).sum().item()
            total += yb.size(0)
    return loss_tot / total, aciertos / total


EPOCHS = 10
hist_pt = {'loss': [], 'val_loss': [], 'acc': [], 'val_acc': []}
for epoch in range(1, EPOCHS + 1):
    tr_loss, tr_acc = run_epoch(train_loader, entrenar=True)
    va_loss, va_acc = run_epoch(val_loader, entrenar=False)
    hist_pt['loss'].append(tr_loss); hist_pt['val_loss'].append(va_loss)
    hist_pt['acc'].append(tr_acc);   hist_pt['val_acc'].append(va_acc)
    print(f"Época {epoch:2d}/{EPOCHS} | loss={tr_loss:.4f} acc={tr_acc:.4f} | "
          f"val_loss={va_loss:.4f} val_acc={va_acc:.4f}")
    scheduler.step()

test_loss, test_acc = run_epoch(test_loader, entrenar=False)

print(f"Accuracy de entrenamiento: {hist_pt['acc'][-1] * 100:.2f}%")
print(f"Accuracy de validación: {hist_pt['val_acc'][-1] * 100:.2f}%")
print(f"Accuracy de test: {test_acc * 100:.2f}%")

# TODO 5: curvas de aprendizaje y precisión en test
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 3))

ax1.plot(hist_pt['loss'], marker='o', label='entrenamiento')
ax1.plot(hist_pt['val_loss'], marker='o', label='validación')
ax1.set_title('PyTorch — Pérdida'); ax1.set_xlabel('época'); ax1.set_ylabel('loss')
ax1.legend(); ax1.grid(alpha=0.3)

ax2.plot(hist_pt['acc'], marker='o', label='entrenamiento')
ax2.plot(hist_pt['val_acc'], marker='o', label='validación')
ax2.set_title('PyTorch — Precisión'); ax2.set_xlabel('época'); ax2.set_ylabel('accuracy')
ax2.legend(); ax2.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# TODO 6: matriz de confusión
# from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
model.eval()
y_pred = []
y_true = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        logits = model(images)
        predicciones = logits.argmax(1).cpu().numpy()
        y_pred.extend(predicciones)
        y_true.extend(labels.numpy())
        pass

cm = confusion_matrix(y_true, y_pred)

plt.imshow(cm, cmap='Blues')
plt.colorbar()
plt.xticks(range(10)); plt.yticks(range(10))
plt.xlabel('Predicción'); plt.ylabel('Etiqueta real')
plt.title('Matriz de confusión - PyTorch')
for i in range(10):
    for j in range(10):
        plt.text(j, i, cm[i, j], ha='center', va='center',
                 color='white' if cm[i, j] > cm.max() / 2 else 'black', fontsize=8)
plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred, digits=3))

"""###Comparación de Modelos
|Modelo            |Entrenamiento     |Validación        |Test         |
|------------------|------------------|------------------|-------------|
|TensorFlow        |36.54%            |38.10%            |39.23%       |
|PyTorch           |57.02%            |57.00%            |55.33%       |

Se observa en la tabla como la precisión de ambos modelos en entrenamiento y validación lo supero PyTorch, ya que la diferencia es mínima 0.02%.
El Modelo PyTorch,obtuvo mejor dsempeño con el 55.33% de precisión en test en comparación el 39.23% que obtuvo TensorFlow.
"""