# -*- coding: utf-8 -*-
"""Actividad_2_Clustering_GMM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGmtskkqSocG-tDFn2gvh4hUXODQ4kOx

<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Actividad 2: Clustering por Gaussian Mixture Models</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> En esta actividad construiras un clustering basado en GMM.
</div>

<div style="margin-top:10px;">
<b>Instrucciones generales: leea y responda los siguientes incisos</b>
<ul>
</ul>
</div>

**1.** Utilice GMM para la segmentación de clientes en el análisis de la cesta de la compra del siguiente dataset `customer_shopping.csv`. Emplee GMM para agrupar a los clientes según su comportamiento de compra. Una vez agrupados, podrá crear promociones dirigidas y recomendaciones personalizadas para cada segmento.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

import warnings
warnings.filterwarnings("ignore")

"""##Cargamos el dataset"""

df_customer = pd.read_csv('customer_shopping.csv')
df_customer.info()
df_customer.head()

faltante_c = df_customer.isnull().sum()
print(f"Total de valores nulos: ,{faltante_c}")

"""##Escalamiento y selección de características, utilice las columnas 'Bread','Milk','Eggs','Beer','Chips'

Para ello, se deben preparar las variables por lo que se debe eliminar de las columnas 'Customer' porque es un string.
"""

#Aquí eliminamos la columna 'Customer'
columns_productos = ['Bread','Milk','Eggs','Beer','Chips']
datos = df_customer[columns_productos]
print(datos.head())

from sklearn.preprocessing import StandardScaler,MinMaxScaler

normal=MinMaxScaler()
X = normal.fit_transform(datos)

"""## Entrene el modelo por GMM utilice métricas para saber cuantos componentes elegir"""

from sklearn.mixture import GaussianMixture
#Se probo con 4, 6 y 10 componentes
#Nos quedamos con 4

gmm = GaussianMixture(n_components=4, covariance_type='full', random_state=42)
gmm.fit(X)
labels = gmm.predict(X)                         # asignación dura (cluster más probable)
probabilidad = gmm.predict_proba(X)             # asignación suave (probabilidades)

print('Pesos de la mezcla:', np.round(gmm.weights_, 3))
print('Probabilidades de los primeros 10 Clientes:\n', np.round(probabilidad[:10], 4))

from sklearn.metrics import silhouette_score

predicciones = gmm.predict(X)
responsabilidades = gmm.predict_proba(X)
print(f'Log-verosimilitud media: {gmm.score(X):.3f}')
print(f'Convergencia: {gmm.converged_} en {gmm.n_iter_} iteraciones')
print(f'Silueta de las etiquetas duras: {silhouette_score(X, predicciones):.3f}')

# Las filas de la matriz de responsabilidades siempre deben sumar 1.
print('Suma de responsabilidades, primeras 10 observaciones:', responsabilidades[:3].sum(axis=1).round(10))

# Muestre el perfil de los clusters
df_perfil = df_customer[['Customer', 'Bread', 'Milk', 'Eggs', 'Beer', 'Chips']].copy()
df_perfil['Cluster'] = labels
print(df_perfil.head())

# Calculo el promedio por variable de cada clúster del dataframe
df_perfil = df_customer[columns_productos].copy()
df_perfil['Cluster'] = labels
perfil_clusters = df_perfil.groupby('Cluster')[columns_productos].mean()

print(perfil_clusters.round(2))

tamaño_clusters = df_perfil['Cluster'].value_counts().sort_index()

print("Número de clientes por cluster:")
print(tamaño_clusters)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
df_cn = pd.DataFrame(X_pca, columns=['X', 'Y'])

df_cn['Cluster'] = labels

plt.figure(figsize=(5, 4))
plt.scatter(df_cn['X'], df_cn['Y'], c=df_cn['Cluster'], cmap='viridis', s=20)
plt.title('Segmentación de clientes mediante GMM')
plt.xlabel('Componente principal 1')
plt.ylabel('Componente principal 2')

plt.show()

df_customer.info()

# Cree un nuevo cliente con la misma estructura del dataframe original
nuevo_cliente = pd.DataFrame({
    'Customer': ['Cliente_Nuevo'],
    'Bread': [5],
    'Milk': [2],
    'Eggs': [4],
    'Beer': [0],
    'Chips': [3]
})

print(nuevo_cliente)

nuevo_cliente_X = nuevo_cliente[columns_productos]
print(nuevo_cliente_X)

# Prediga el cluster al que pertenece este nuevo cliente

cluster_cliente_nuevo = gmm.predict(nuevo_cliente_X)
print(f"Clúster del nuevo cliente: {cluster_cliente_nuevo[0]}")

predict_proba = gmm.predict_proba(nuevo_cliente_X)
print(f"Probabilidad de pertenencia a cada clúster: {(np.round(predict_proba,4))}")

# En función al resultado, cree una recomendación a este nuevo cliente
# De acuerdo a cada perfil de clúster, al pertencer al [0], indica:
# Consume demasiado BREAD, EGGS y MILK, por lo que la promoción puede
# ser para el desayuno, en la compra de los tres productos.

"""**2.-**  Obtenga un modelo de clustering para el dataset `healthcare_dataset.csv` para obtener una agrupación de pacientes sanitarios mediante GMM: Los hospitales a menudo necesitan agrupar a pacientes con características similares para: identificar pacientes de alto riesgo, personalizar planes de tratamiento, optimizar la asignación de recursos y mejorar la gestión sanitaria."""

#Cargamos el dataset
df_health = pd.read_csv('healthcare_dataset.csv')
df_health.info()
df_health.head()

faltante_h = df_health.isnull().sum()
print(f"Total de valores nulos: ,{faltante_h}")

"""# Escalamiento y selección de características"""

# ¿Qué hacemos si tenemos columnas categoricas y numéricas y queremos utilizarlas en el clustering?
# hay que convertir y transformar a números

#Puedo identificar cuantas categorías tiene cada variable
df_health.nunique()

#Identificar cuales son las categorías de las variables
for col in df_health.columns:
    print(df_health[col].value_counts().head(10))
    print('-' * 30)

# Para el procesamiento de la información no voy a utlizar todas las columnas (variables) por lo que hay que analizar cual nos sirven y cual no
# Descarto:
# 'Name','Room Number','Doctor','Hospital' no se pueden categorizar y no proporcionan mayor información.

# Conservo:
# Se pueden categorizar y ordenar
# 'Age', puedo obtener características niño, adulto y adulto mayor.
# 'Billing Amount' podemos obtener promedio o desviaciones de gastos o costo de atención.
# 'Date of Admission', 'Discharge Date', nos puede dar el tiempo de estancia.
# 'Gender', para clasificar hombre o mujer.
# 'Blood Type', se puede clasificar, o tipos de sangre.
# 'Medical condition', dice el perfil exacto del paciente, tiene 6 categorías.
# 'Admission Type', tiene 3 categorías.
# 'Insurance Provider', tiene 5 categorías.
# 'Medication' tiene 5 categorías.
# 'Test Resultados' tiene 3 categorías.

# Acción para obtener la estancia del paciente
df_health["Date of Admission"] = pd.to_datetime(df_health["Date of Admission"])
df_health["Discharge Date"] = pd.to_datetime(df_health["Discharge Date"])

df_health["Length of Stay"] = (
    df_health["Discharge Date"] -
    df_health["Date of Admission"]
).dt.days

print("\nEstancia en días:")
print(df_health["Length of Stay"].describe())

columnas_eliminar = ["Name", "Room Number", "Doctor", "Hospital", "Date of Admission", "Discharge Date"]
df_health = df_health.drop(columns=columnas_eliminar)

df_health.head()

# Se revisa que las columnas numéricas no haya datos negativos:
print("Valores negativos de Age:", (df_health["Age"] < 0).sum())
print("Valores negativos de Billing Amount:", (df_health["Billing Amount"] < 0).sum())
print("Valores negativos de Length of Stay:", (df_health["Length of Stay"] < 0).sum())

# Como si hay en Billing Amount
# Resultaron 108 es una mínima parte, prefiero eliminarlos y quedarme con los montos de facturación positivos >0.
# defini otro DataFrame
df_hn = df_health[df_health["Billing Amount"] >= 0].copy()

#Comprobación de eliminación de registros
print(df_hn.shape)
print((df_hn["Billing Amount"] < 0).sum())

df_hn.info()

#Separar variables numéricas y categóricas para procesar agrupadas todas las columnas.
columnas_numericas = ["Age","Billing Amount","Length of Stay"]
columnas_categoricas = ["Gender","Blood Type","Medical Condition","Insurance Provider","Admission Type","Medication","Test Results"]

#Para procesar las columnas numéricas se utilizará StandardScaler()
#Para procesar las columns categóricas se utilizará OneHotEncoder()

columnas_numericas

columnas_categoricas

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Junto los dos grupos de categorías con el ColumnTransformer:
preprocesador = ColumnTransformer(transformers=[
        ("numericas", StandardScaler(), columnas_numericas),
        ("categoricas", OneHotEncoder(handle_unknown="ignore"), columnas_categoricas)])

X = preprocesador.fit_transform(df_hn)
X_dense = X.toarray()

# Entrene el modelo por GMM utilice métricas para saber cuantos componentes elegir y cree una columna para asignar el cluster
from sklearn.mixture import GaussianMixture

gmm_10 = GaussianMixture(n_components=10, covariance_type='full', random_state=42)
gmm_10.fit(X_dense)
labels = gmm_10.predict(X_dense)                         # asignación dura (cluster más probable)
probabilidad = gmm_10.predict_proba(X_dense)             # asignación suave (probabilidades)

print('Pesos de la mezcla:', np.round(gmm_10.weights_, 4))
print('Probabilidades de los 10 primeros pacientes:\n', np.round(probabilidad[:10], 6))

df_hn["Cluster"] = labels

print("\nCantidad de pacientes por cluster:") #Aportación de IA
print(df_hn["Cluster"].value_counts().sort_index())

#Promedio de las columnas numéricas
perfil_numerico = df_hn.groupby("Cluster")[["Age", "Billing Amount", "Length of Stay"]].mean()
print(perfil_numerico.round(2))

#Cree una tabla para mostrar como queda los Clúster con las columnas categóricas
tabla_categoricas = pd.DataFrame()

for variable in columnas_categoricas:
    valores = (df_hn.groupby("Cluster")[variable].agg(lambda x: x.mode().iloc[0]))

    tabla_categoricas[variable] = valores

tabla_categoricas = tabla_categoricas.T # Transponer para que las variables sean filas
tabla_categoricas.columns = [f"Clúster {c}" for c in tabla_categoricas.columns]

tabla_categoricas

# Cree un nuevo paciente con algunos valores en base a las columnas elegidas
nuevo_paciente = pd.DataFrame({
    "Age": [49],
    "Gender": ["Female"],
    "Blood Type": ["O+"],
    "Medical Condition": ["Hypertension"],
    "Insurance Provider": ["Cigna"],
    "Billing Amount": [33950],
    "Admission Type": ["Urgent"],
    "Medication": ["Lipitor"],
    "Test Results": ["Abnormal"],
    "Length of Stay": [13]
})

nuevo_paciente

#proceso todo otra vea, pero para el nuevo paciente np
# preproceso la transformación, con 10 componentes
X_np = preprocesador.transform(nuevo_paciente)
X_np_dense = X_np.toarray()
cluster_np = gmm_10.predict(X_np_dense)
print("El nuevo paciente pertenece al clúster:", cluster_np[0])

# Asignación suave (probabilidades)
probabilidades_np = gmm_10.predict_proba(X_np_dense)
print("Probabilidades de pertenencia:")
print(np.round(probabilidades_np, 6))

# Muestre graficas de sus resultados

conteo_clusters = df_hn["Cluster"].value_counts().sort_index()

plt.figure(figsize=(6, 3))
plt.bar(conteo_clusters.index, conteo_clusters.values)

plt.xlabel("Clúster")
plt.ylabel("Pacientes")
plt.title("Pacientes por Clúster")
plt.xticks(range(10))
plt.show()

promedio_facturacion = df_hn.groupby("Cluster")["Billing Amount"].mean()

plt.figure(figsize=(7, 3))
plt.bar(promedio_facturacion.index, promedio_facturacion.values)

plt.xlabel("Clúster")
plt.ylabel("Facturación promedio")
plt.title("Facturación promedio por clúster")
plt.xticks(range(10))

plt.show()

edad_admision = (df_hn.groupby(["Cluster", "Admission Type"])["Age"].mean().unstack())

edad_admision.plot(kind="bar", figsize=(10, 4))

plt.xlabel("Clúster")
plt.ylabel("Edad promedio")
plt.title("Edad promedio por clúster y tipo de admisión")
plt.xticks(rotation=0)
plt.legend(title="Tipo de admisión")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 3))

plt.bar(range(10), probabilidades_np[0])

plt.xlabel("Clúster")
plt.ylabel("Probabilidad")
plt.title("Probabilidad de pertenencia del nuevo paciente")
plt.xticks(range(10))

plt.show()

#Abajo los ejemplos de 5 y 20 componentes pero me que con 10 clúster

gmm_5 = GaussianMixture(n_components=5, covariance_type='full', random_state=42)
gmm_5.fit(X_dense)
labels = gmm_5.predict(X_dense)                         # asignación dura (cluster más probable)
probabilidad = gmm_5.predict_proba(X_dense)             # asignación suave (probabilidades)

print('Pesos de la mezcla (pi_k):', np.round(gmm_5.weights_, 4))
print('Probabilidades de los 10 primeros pacientes:\n', np.round(probabilidad[:10], 6))

df_hn["Cluster"] = labels

print("\nCantidad de pacientes por cluster:") #Aportación de IA
print(df_hn["Cluster"].value_counts().sort_index())

gmm_20 = GaussianMixture(n_components=20, covariance_type='full', random_state=42)
gmm_20.fit(X_dense)
labels = gmm_20.predict(X_dense)                         # asignación dura (cluster más probable)
probabilidad = gmm_20.predict_proba(X_dense)             # asignación suave (probabilidades)

print('Pesos de la mezcla (pi_k):', np.round(gmm_20.weights_, 4))
print('Probabilidades de los 10 primeros pacientes:\n', np.round(probabilidad[:10], 6))

df_hn["Cluster"] = labels

print("\nCantidad de pacientes por cluster:") #Aportación de IA
print(df_hn["Cluster"].value_counts().sort_index())