# -*- coding: utf-8 -*-
"""Actividad_1_Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2Rba4ezaJ5Zs_Bwv36VdaOVCaoP0oKc

<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Actividad 1: Implementación de un modelo por Random Forest</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> En esta actividad construiras un clasificadore basados en **Random Forest** para predecir la **aceptabilidad/seguridad de un automóvil**.
</div>

<div style="margin-top:10px;">
<b>Instrucciones generales:</b>
<ul>
<li>Entrenar dos modelos (con pocos y con muchos árboles) para observar cómo mejora la exactitud, demostrar el proceso de **selección de características** basado en la importancia de variables, y reconstruir el modelo con las variables más relevantes. </li>

</ul>
</div>
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Random Forest** (bosque aleatorio) es un algoritmo de **aprendizaje supervisado** basado en **ensamble** (*ensemble learning*). Tiene dos variantes: una para **clasificación** y otra para **regresión**. Es uno de los algoritmos más flexibles y fáciles de usar.

Construye **múltiples árboles de decisión** sobre distintas muestras de los datos, obtiene la predicción de cada árbol y selecciona la mejor solución mediante **votación**. Además, es un excelente indicador de la **importancia de las variables**.

> Al combinar muchos árboles se forma un "bosque"; de ahí el nombre **Random Forest**. Cuantos **más árboles**, mayor suele ser la exactitud (hasta estabilizarse).

#### Selección de características con Random Forest

El Random Forest permite **ordenar la importancia** de las variables. Durante el entrenamiento, se registra el **error out-of-bag (OOB)** y se promedia sobre el bosque.

Para medir la importancia de la característica *j*, se **permutan** sus valores en los datos y se recalcula el error OOB sobre ese conjunto perturbado. La **importancia** es la diferencia promedio de error OOB antes y después de la permutación, normalizada por su desviación estándar.

Las características que producen valores **grandes** de esta puntuación son más importantes. Con base en ella, conservaremos las más relevantes y descartaremos las menos útiles.

**Planteamiento del problema**

El objetivo es **predecir la aceptabilidad/seguridad de un automóvil** con un clasificador Random Forest en Python y scikit-learn, usando el [**Car Evaluation Data Set**](http://archive.ics.uci.edu/ml/datasets/Car+Evaluation) de la UCI.

El **Car Evaluation Data Set** relaciona la evaluación del automóvil (`class`) con **seis atributos de entrada**:

| Variable | Descripción | Valores |
|---|---|---|
| `buying` | Precio de compra | vhigh, high, med, low |
| `maint` | Costo de mantenimiento | vhigh, high, med, low |
| `doors` | Número de puertas | 2, 3, 4, 5more |
| `persons` | Capacidad de personas | 2, 4, more |
| `lug_boot` | Tamaño de la cajuela | small, med, big |
| `safety` | Seguridad estimada | low, med, high |
| `class` | **Objetivo:** evaluación | unacc, acc, good, vgood |
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

# Dataset real de la UCI (se descarga al vuelo)
#url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
#df = pd.read_csv(url, header=None)
# Alternativa local: df = pd.read_csv('C:/datasets/car.data', header=None)

df = pd.read_csv('car.data', header=None)

"""## 1.- Análisis exploratorio de datos"""

# Primeras filas (columnas aún sin nombre)
df.head()

col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names
df.head()

df.info()

# Distribución de frecuencias
for col in col_names:
    print(df[col].value_counts())
    print('=' * 40)

"""### Variable objetivo `class` y valores faltantes
La variable objetivo es **ordinal** (unacc < acc < good < vgood).
"""

#La variable 'class' y sus categorías
df['class'].value_counts()

faltante = df.isnull().sum()
print(f"Total de valores nulos: ,{faltante}")

"""## 2. Definir variables predictoras y objetivo"""

#Variable Objetivo
y = df['class']

#Variables Predictoras [todas excepto 'class']
X = df.drop(['class'], axis=1)

"""## 3. Dividir en entrenamiento y prueba"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print('Entrenamiento:', X_train.shape, '| Test:', X_test.shape)

"""## 4. Ingeniería de características (codificación)

Todas las variables son **categóricas ordinales**; las convertimos a números con `OrdinalEncoder` de scikit-learn (sin dependencias externas).
"""

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
X_train = pd.DataFrame(encoder.fit_transform(X_train), columns=X.columns, index=X_train.index)
X_test = pd.DataFrame(encoder.transform(X_test), columns=X.columns, index=X_test.index)

X_train.head()

X_test.head()

"""## 5. Random Forest con pocos árboles (modelo 1)

Entrena un bosque con **10 árboles** para tener una referencia.

"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

#Árbol de referencia
#tree = DecisionTreeClassifier(random_state=0).fit(X_train, y_train)

# Modelo 1: Random Forest con 10 Árboles con OOB score activado
rf_mod1 = RandomForestClassifier(
    n_estimators=10, max_features='sqrt', oob_score=True,
    random_state=42, n_jobs=-1,
).fit(X_train, y_train)

print('Random Forest con 10 Árboles -> test accuracy:', round(accuracy_score(y_test, rf_mod1.predict(X_test))*100, 1))
print('Random Forest con 10 Árboles -> OOB score   :', round((rf_mod1.oob_score_)*100, 1))

y_pred = rf_mod1.predict(X_train)

y_pred

"""## 6. Random Forest con muchos arboles `n_estimators=100`

Entrena un modelo con **100 árboles** y comenta lo que puedas observar.
"""

# Modelo 2: Random Forest con 100 Árboles con OOB score activado
rf_mod2 = RandomForestClassifier(
    n_estimators=100, max_features='sqrt', oob_score=True,
    random_state=10, n_jobs=-1,
).fit(X_train, y_train)

print('Random Forest con 100 Árboles -> test accuracy:', round(accuracy_score(y_test, rf_mod2.predict(X_test))*100, 1))
print('Random Forest con 100 Árboles -> OOB score   :', round((rf_mod2.oob_score_)*100, 1))

y_pred = rf_mod2.predict(X_test)

y_pred

"""#### Comentarios
Se mantienen todos los parametros a excepción de n_estimator (número de árboles), en el Modelo 1 son 10 árboles y en el Modelo 2 son 100 árboles.

* Modelo 1--> 10  árboles: 94.5% Test Accuracy (exactitud)
* Modelo 2--> 100 árboles: 96.2% Test Accuracy (exactitud)
Diferencia a favor del modelo 2 con +1.7%, indicando un mejoramiento en la exactitud.

* Modelo 1--> 10  árboles: 89.9% OOB score
* Modelo 2--> 100 árboles: 97.5% OOB score
Diferencia a favor del modelo 2 con +7.6%, indicando reducción en las variaciones de cada árbol quedando a 2.5% de una estabilidad al 100%.

Con ello, el modelo2 es más preciso y estable, muestra un mejor desempeño. Aunque se podría decir que es ligeramente mejor, porque el entrenamiento es considerable con incremento de 10 veces.

## 7. Importancia de las características

Usa el atributo `feature_importances_` del bosque para ordenar las variables por relevancia.
"""

# Importancia de variables del bosque con 10 Árboles, Modelo 1
imp_var1 = (pd.Series(rf_mod1.feature_importances_, index=X.columns).sort_values(ascending=False)*100).round(1)
print('\nMODELO 1 --> Importancia de Variables Ordenadas, según su relevancia:\n', imp_var1)
print('\nSuma de Importancias:', round(imp_var1.sum(),1),'%')

# Importancia de variables del bosque con 100 Árboles, Modelo 2
imp_var2 = (pd.Series(rf_mod2.feature_importances_, index=X.columns).sort_values(ascending=False)*100).round(1)
print('\nMODELO 2 --> Importancia de Variables Ordenadas, según su relevancia:\n', imp_var2)
print('\nSuma de Importancias:', round(imp_var2.sum(),1),'%')

"""## 8. Visualizar la importancia de las características"""

plt.figure(figsize=(8, 4))
imp_var1.plot.barh(color='#2E9AFE')
plt.xlabel('Importancia (reducción de impureza)')
plt.title('Importancia de variables — Modelo 1 Random Forest (Automóviles)')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
imp_var2.plot.barh(color='#16a085')
plt.xlabel('Importancia (reducción de impureza)')
plt.title('Importancia de variables — Modelo 2 Random Forest (Automóviles)')
plt.tight_layout()
plt.show()

"""## 9. Reconstruir el modelo con las características seleccionadas

Elimina la variable **menos importante**, reconstruye el modelo y compara la exactitud.
"""

#La variable menos importante es 'doors' con tan solo 6.6% de relevancia

X_var_elim = X.drop(['doors'], axis=1)

# Nuevo conjunto de variables sin 'doors'
print(X_var_elim.columns)

#Vuelvo a dividir las variables para entrenamiento y prueba,
X_train_e, X_test_e, y_train_e, y_test_e = train_test_split(X_var_elim, y, test_size=0.2, random_state=42)
print('Entrenamiento:', X_train_e.shape, '| Test:', X_test_e.shape)

X_train_e.head()

#Utilizamos el OrdinalEncord
encoder = OrdinalEncoder()
X_train_e = pd.DataFrame(encoder.fit_transform(X_train_e), columns=X_var_elim.columns, index=X_train_e.index)
X_test_e = pd.DataFrame(encoder.transform(X_test_e), columns=X_var_elim.columns, index=X_test_e.index)

X_train_e.head()

# Utilizamos el Modelo 2
# Modelo 3: Random Forest con 100 Árboles con OOB score activado (sin la variable 'doors')
rf_mod3 = RandomForestClassifier(
    n_estimators=100, max_features='sqrt', oob_score=True,
    random_state=10, n_jobs=-1,
).fit(X_train_e, y_train_e)

print('Random Forest con 100 Árboles -> test accuracy:', round(accuracy_score(y_test_e, rf_mod3.predict(X_test_e))*100, 1))
print('Random Forest con 100 Árboles -> OOB score   :', round((rf_mod3.oob_score_)*100, 1))

y_pred_e = rf_mod3.predict(X_test_e)

y_pred_e

# Importancia de las variables del Modelo 3 del bosque con 100 Árboles
imp_var3 = (pd.Series(rf_mod3.feature_importances_, index=X_var_elim.columns).sort_values(ascending=False)*100).round(1)
print('\nMODELO 3 --> Importancia de Variables Ordenadas, según su relevancia:\n', imp_var3)
print('\nSuma de Importancias:', round(imp_var3.sum(),1),'%')

plt.figure(figsize=(8, 4))
imp_var3.plot.barh(color='#9A32CD')
plt.xlabel('Importancia (reducción de impureza)')
plt.title('Importancia de variables — Modelo 3 Random Forest (Automóviles)')
plt.tight_layout()
plt.show()

"""### Comentarios
Los resultados del Modelo 3 con la eliminación de la variable 'doors' que es la menos importante:

* Modelo 2 tiene seis variables, Modelo 3 tiene cinco variables.
##### Test Accuracy (exactitud)
* Modelo 2--> 100 árboles y 6 variables: 96.2%.
* Modelo 3--> 100 árboles y 5 variables: 92.5%.
Diferencia a favor del modelo 2 con +3.7%, indicando un decremento en la exactitud en el Modelo 3.

##### OOB score
* Modelo 2--> 100 árboles:97.5% OOB score
* Modelo 3--> 100 árboles: 94.5% OOB score
Diferencia a favor del modelo 2 con +3.0%, indicando mayor aumento en las variaciones de cada árbol en el Modelo 3.

Aunque se eliminó la variable menos importante o relevante 'doors' del modelo, tuvo un gran impacto en los resultados del Test y OOB score disminuyendo, por lo que se puede decir que si aporta información útil al modelo. Porque al quitar 'doors' bajo el accuracy y afecto el desempeño.

## 10. Crea un Reporte de clasificación

Muestra **precision**, **recall**, **f1-score** y **support** por clase.

### Reporte de Clasificación del Modelo 3 sin 'doors' del bosque con 100 árboles
"""

from sklearn.metrics import classification_report

print(classification_report(y_test_e, y_pred_e))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Predicciones
y_pred_e = rf_mod3.predict(X_test_e)

# Matriz de confusión
cm = confusion_matrix(y_test_e, y_pred_e)

# Mostrar matriz
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=rf_mod3.classes_
)

disp.plot(cmap='Blues')
plt.title('Matriz de Confusión — Modelo 3 Random Forest (100 árboles)')
plt.show()

"""### Comentarios
* unacc: es la categoría de 'class' mejor identificada tiene resultados superiores a 98, por lo que el modelo identifica 235 automóviles NO ACEPTABLES.
* acc: es la segunda categoría con mejor precisión pero en recall es la segunda inferior dejando el 22% no precisa si son acceptables los automóviles, sólo identifica a 83.
* good presenta el desempeño más bajo con una precisión del 39% con solo 11 casos.

De forma general, aún cuando se tiene una precisión alta de los automóviles no aceptables y de los aceptablles, se tiene muy baja la precisión cuales son buenos.
"""

