# -*- coding: utf-8 -*-
"""Tarea_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XruQiX5rAybrajWA9bCjz5MsOvhgP0EY

<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Tarea 1: Investigación de HDBSCAN y OPTICS</h1>
<br style="clear:both"/>
</div>

**1.** Realice una investigación sobre los algoritmos HDBSCAN y OPTICS. Explique sus fundamentos, parámetros, funcionamiento, ventajas y limitaciones, e incluya imágenes, diagramas y ejemplos que faciliten su comprensión.

## **HDBSCAN (Hierarchical Density-Based Spatial Clustering of Applications with Noise)**

### Descripción y Fundamentos
Algoritmo de clustering basado en densidad, se busca **agrupar observaciones o puntos de zonas o regiones con alta concentración de datos** denominandose cluster, las **observaciones que no se agrupan** porque están **alejadas o aisladas** se consideran **ruido**, pues no pertenecen a ningún grupo.

Considera una estructura jerárquica de agrupaciones con diferentes densidades; con aplicación de métricas y parámetros se pueden identificar las agrupaciones más estables.

**HDBSCAN es una extensión de DBSCAN**

### Funcionalidad
Datos **->** Analiza Densidad **->** Construye Jerarquia **->** Identifica Clusters Estables **->** Clasifica Ruido

### Parámetros (principales)

* **min_cluster_size**: número mínimo de observaciones que debe tener un cluster. Al aumentar el valor;se requieren agrupaciones más grandes, se disminuye la identificación de agrupaciones más pequeñas y pueden aumentar los puntos "ruido". Al disminuir el valor; se identifican más los grupos pequeños, se generan más grupos y se dispersa los resultados.

* **min_samples:** controla la identificaión de las observacione a las zonas densas. Un valor mayor crea un algoritmo más conservador.

* **metric:** la metrica calcula la distancia entre observaciones, la más representativa es la 'euclidiana'.

* **eps**: radio máximo para considerar dos puntos vecinos.

### Atributos (principales):
1. **labels_**: etiquetas de cluster para cada punto en el conjunto de datos.
2. **probabilities_**: fuerza con la que cada muestra pertenece al grupo que ha sido asignado.
3. **n_features_in**: número de características observadas durante el entrenamiento.

### Ventajas

1. No requiere quse se le indique el número de clusters.
2. Detecta ruido, observaciones atípicas.
3. Encuentra cluster de diferentes densidades.
4. No requiere un radio -eps- como dbscan.
5. Puede valorarse la estabilidad en los cluster.

### Desventajas
1. Puede generar demasiado ruido.
2. Sensible a los parámetros.
3. Es un poco más difícil de interpretar, utiliza concepto de densidad, jerarquía y estabilidad.
"""

#Ejemplo: aplicado al conjunto de datos 'digits' de scikit-learn
import numpy as np
from sklearn.cluster import HDBSCAN
from sklearn.datasets import load_digits
X, _ = load_digits(return_X_y=True) #Contiene las características de las imágenes.
hdb = HDBSCAN(copy=True, min_cluster_size=20) #Indica que un cluster debe tener al menos 20 observaciones para ser considerado un grupo.
hdb.fit(X)
hdb.labels_.shape == (X.shape[0],)
np.unique(hdb.labels_).tolist()

"""El ejemplo indica que del conjunto de datos 'digit' genero 8 cluster del 0 - 7 y -1 = ruido.

## **OPTICS (Ordering Points To Identify the Clustering Structure)**

### Descripción y Fundamentos
**Algoritmo de clustering basado en densidad**, **identifica la estructura de densidad de datos** sin depender de un único valor de eps (epsilon). Determina **qué tan densa es la conexión entre las observaciones**.

Para ello, genera un ordenamiento de las observaciones y calcula los valores relacionados con la densidad.

Uno de los conceptos que se registara es **Reachability distane** distancia de alcanzabilidad, indica qué tan difícil es llegar desde un punto a otro considerando la densidad de la zona o región.

### Parámetros (pincipales)

* **min_samples**; int > 1 or float between 0 and 1, default=5. Indica el númer mínimo de muestra utilizado para determinar la densidad local. Un valor mayor, exige más al algoritmo con respecto a la densidad.
* **max_eps**; float, default=np.inf. Es la distancia máxima que se considera para buscar vecinos.
* **metric**; str or callable, default=’minkowski’. Métrica de distancia, la más representativa es la 'euclidiana'.
* **cluster_method**; {‘xi’, ‘dbscan’}, default=’xi’. Define como se extraen los clusters a partir de la estructura encontrada. El método 'xi' identifica cambios importantes en la estructura de alcanzabilidad para separar clusters.
* **min_cluster_size**: int > 1 or float between 0 and 1, default=None. Mínimo número de ejemplares en un cluster.
* **xi**:float between 0 and 1, default=0.05. Determina la pendiente mínima en el gráfico de alcanzabilidad que constituye el límite de un clúster.

### Atributos (principales)

1. labels_: ndarray of shape (n_samples,). Etiquetas de clúster para cada punto en el conjunto de datos proporcionado a fit().
2. reachability_: ndarray of shape (n_samples,). Distancias de accesibilidad por muestra, indexadas por orden de objeto.
3. ordering_ndarray of shape (n_samples,). La lista de índices de muestra ordenados por clúster.
4. n_features_: in_int. Número de características observadas durante el entrenamiento.

### Funcionalidad

Datos **->** Calcula densidad local **->** Ordena las observaciones **->** Calcula distancias de alcanzabilidad **->** Construye estructura de densidad **->**
Extrae clusters **->** Identifica ruido

### Ventajas
1. No necesita definir directamente el número de clusters.
2. Maneja diferente densdidades.
3. No depende de un punico eps.
4. Permite visualizar la estructura.

### Desventajas
1. Díficil de interpretar.
2. Depende de sus parámetros.
3. Puede generar mucho ruido.
"""

#Ejemplo: aplicando scikit-learn
from sklearn.cluster import OPTICS
import numpy as np
# se tienen 6 observaciones y dos característica (6 registro, 2 columnas)
X = np.array([[1, 2], [2, 5], [3, 6],
              [8, 7], [8, 8], [7, 3]])
clustering = OPTICS(min_samples=2).fit(X) #indica que se utiliza un mínimo de 2 observaciones para determinar la densidad local
clustering.labels_ #muestra el cluster asignado a cada observación.

"""El cluster 0 es para la observación 1, 2, 3 y el cluster 1 a la observación 4, 5 y 6.

**2.-** Posteriormente, aplique ambos algoritmos al conjunto de datos `wine-clustering.csv`. Analice y visualice la distribución de las variables, prepare adecuadamente los datos y obtenga los clusters identificados por cada modelo. Compare sus resultados mediante gráficas y métricas apropiadas, considerando aspectos como el número de clusters, la cantidad de puntos considerados ruido, la estabilidad y la calidad de las agrupaciones.

---
"""

from google.colab import drive
drive.mount('/content/drive')

#!pip install -U scikit-learn hdbscan

import numpy as np
import pandas as pd
import hdbscan
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.cluster import HDBSCAN, OPTICS
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

"""# A. Carga y exploración de datos"""

df_wine = pd.read_csv('wine-clustering.csv')
print("Dimensiones:", df_wine.shape)
df_wine.info()
df_wine.head()

valores_nulos = df_wine.isnull().sum()
print(f"Total de valores nulos: ,{valores_nulos}")

df_wine.describe()

"""# B. Distribución de Variables"""

df_wine.hist(figsize=(10, 8), bins=20)

plt.suptitle("Distribución de las variables de Wine", fontsize=12)
plt.tight_layout()
plt.show()

"""# C. Estandarizar las variables"""

# Con el transform los valores de las variables se estandarizan a una escala:
# media = 0 y una desviación estándar = 1
# Así las variables con valores disparados quedan a escalas semejantes para comparar.

X = df_wine.copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
display(X_scaled.head())

"""# E. Parámetros y Clúster Identificados con HDBSCAN"""

#Clustering HDBSCAN
#Parámetros
clusterer = hdbscan.HDBSCAN(min_cluster_size=10, min_samples=4, metric='euclidean')
#clusterer = hdbscan.HDBSCAN(min_cluster_size=8, min_samples=4, metric='euclidean')
clusterer.fit(X_scaled)
labels_hds = clusterer.labels_

print("Etiquetas de los clusters HDBSCAN:")
print(labels_hds)

n_clusters_hds = len(set(labels_hds)) - (1 if -1 in labels_hds else 0)
n_noise_hds = np.sum(labels_hds == -1)

print("Número de clusters por HDBSCAN:", n_clusters_hds)
print("Puntos considerados ruido:", n_noise_hds)
print("Porcentaje de ruido:", n_noise_hds / len(labels_hds) * 100)
print("\nCantidad de observaciones por cluster:")
print(pd.Series(labels_hds).value_counts().sort_index())

#Clustering OPTICS
#Parámetros
#optics = OPTICS(min_samples=5, xi=0.05, min_cluster_size=0.05)
optics = OPTICS(min_samples=4, xi=0.05, min_cluster_size=0.05)
optics.fit(X_scaled)
labels_opt = optics.labels_
print("Etiquetas de los clusters OPTICS:")
print(labels_opt)

n_clusters_opt = len(set(labels_opt)) - (1 if -1 in labels_opt else 0)
n_noise_opt = np.sum(labels_opt == -1)

print("Número de clusters por OPTICS:", n_clusters_opt)
print("Puntos considerados ruido:", n_noise_opt)
print("Porcentaje de ruido:", n_noise_opt / len(labels_opt) * 100)
print("\nCantidad de observaciones por cluster:")
print(pd.Series(labels_opt).value_counts().sort_index())

# Identificar el cluster de cada registros
# Promedio de cada variable por cluster
df_resultado = df_wine.copy()
df_resultado["Cluster_hds"] = labels_hds
df_resultado["Cluster_opt"] = labels_opt
display(df_resultado.head())

perfil_clusters_hds = df_resultado.groupby("Cluster_hds").mean()
perfil_clusters_opt = df_resultado.groupby("Cluster_opt").mean()
display(perfil_clusters_hds)
display(perfil_clusters_opt)

"""# E. Visualizar Clusters (Gráficas)"""

#PCA para representar los resultados en dos dimensiones
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
df_resultado["PCA1"] = X_pca[:, 0]
df_resultado["PCA2"] = X_pca[:, 1]

#Gráfica Cluster HDBSCAN
plt.figure(figsize=(4, 4))
sns.scatterplot(data=df_resultado, x="PCA1", y="PCA2", hue="Cluster_hds", palette="tab10", s=20)
plt.title("Clusters obtenidos mediante HDBSCAN")
plt.xlabel("Componente principal 1")
plt.ylabel("Componente principal 2")
plt.legend(title="Cluster_HDS")
plt.show()

#Gráfica Cluster OPTICS
plt.figure(figsize=(4, 4))
sns.scatterplot(data=df_resultado, x="PCA1", y="PCA2", hue="Cluster_opt", palette="tab10", s=20)
plt.title("Clusters obtenidos mediante OPTICS")
plt.xlabel("Componente principal 1")
plt.ylabel("Componente principal 2")
plt.legend(title="Cluster_HDS")
plt.show()

"""# F. Calidad y Estabilidad de los Cluster"""

# Estabilidad HDBSCAN
# identifica que el Cluster más estable es el que tiene el valor más alto
# Cluster menos estable es el que tiene el valor más bajo.
for i, estabilidad in enumerate(clusterer.cluster_persistence_):
    print(f"Estabilidad del Cluster con HDBSCAN {i}: {estabilidad:.4f}")

#Alcanzabilidad OPTICS
space = np.arange(len(X_scaled))
reachability = optics.reachability_[optics.ordering_]
labels_ordered = optics.labels_[optics.ordering_]

plt.figure(figsize=(7, 4))
plt.plot(space, reachability, marker=".", linestyle="None" )
plt.xlabel("Orden OPTICS")
plt.ylabel("Distancia de Alcanzabilidad")
plt.title("Gráfica de alcanzabilidad - OPTICS")

plt.show()

#Silhouette Score, Métrica de Calidad

#HDBSCAN
mask_hds = labels_hds != -1
labels_hds_sin = labels_hds[mask_hds]
X_hds_sin = X_scaled[mask_hds]

if len(set(labels_hds_sin)) > 1:
    silhouette_hds = silhouette_score(
        X_hds_sin,
        labels_hds_sin)
    print("Silhouette Score con HDBSCAN:", silhouette_hds)
else:
    print("Se requieren al menos 2 clusters para calcular Silhouette HDBSCAN.")

#OPTICS
mask_opt = labels_opt != -1
labels_opt_sin = labels_opt[mask_opt]
X_opt_sin = X_scaled[mask_opt]

if len(set(labels_opt_sin)) > 1:
    silhouette_opt = silhouette_score(
        X_opt_sin,
        labels_opt_sin)
    print("Silhouette Score con OPTICS:", silhouette_opt)
else:
    print("Se requieren al menos 2 clusters para calcular Silhouette OPTICS.")

"""#### Calidad de Cluster HDBSCAN

| Silhouette | Interpretación              |
| ---------- | --------------------------- |
| Cerca de 1 | Clusters muy bien separados |
| 0.5 - 0.7  | Buena separación            |
| 0.25 . 0.5 | Separación moderada         |
| Cerca de 0 | Clusters poco definidos     |
| < 0        | Posible mala asignación     |

**3.-** Finalmente, interprete los resultados y redacte una conclusión argumentada sobre cuál de los dos algoritmos ofrece un mejor desempeño para este

## Resultados y Conclusión

Al aplicar los algoritmos HDBSCAN y OPTICS a los datos wine_clustering.csv se observó diferncias importantes, que se muestran en la siguiente tabla.

Con base en esos resultados, HDBSCAN presentó un mejor desempeño para este cojunto de datos, debido a que logró identifica una mayor cantidad pobervaciones agrupadas en dos cluster, presentó menor ruido y una menor separación. Obtuvo una estructura de agrupamiento más estable con los parámetros establecidos.

Parámetros

HDBSCAN: min_cluster_size=10, min_samples=4, metric='euclidean'

OPTICS: min_samples=4, xi=0.05, min_cluster_size=0.05

TABLA COMPARATIVA

| Descripción       |        HDBSCAN     |     OPTICS     |
| ----------------- | -------------------|----------------|
| Número de Cluster | 2                  | 3              |
| Punto de Ruido    | 58                 | 150            |
| % Ruido           | 32.58%             | 84.26%         |
| Cluster 0         | 34                 | 9              |
| Cluster 1         | 86                 | 8              |
| Cluster 2         | -                  | 11             |
| Silhouette        | 0.352              | 0.577          |
| Estabilidad       | 0.0732 / 0.1458    |                |

De las 178 observaciones , HDBSCAN logró agrupar 120 en dos cluster mientras que OPTICS sólo logro agrupar 28 en tres cluster. Es menor el % de ruido en HDBSCAN con 32.58% que OPTICS con 84.26%. Menciono en un ejercicio con min_samples = 5 OPTICS sólo logró agupar un solo cluster, por lo que se reajusto para realizar comparativas.

En relación a Silhouette HDBSCAN tiene menor separación que OPTICS, 0.35 < 0.57

El cluster 1 de HDBSCAN presentó mayor estabilidad que el cluster 0.
"""